### ISSUE TITLE
Joining trouble

### ISSUE THREAD

**Issue by Marshlyin** [monowii/pictochat#1]
Après avoir entré un username et cliqué sur join, il ne se passe rien. 
Le terminal renvoi : 
`connected ::1`
et la console du navigateur renvoi  
![image](https://user-images.githubusercontent.com/23241558/62471061-1b298d80-b79c-11e9-8b5f-63bad19cd2fb.png)

Npm version : 3.5.2
Node version : 8.10

Toute les dépendances sont installées

**Comment by monowii** [comment]
fixed with commit c5aac271894ebf19743372087eeb13fcca20cece
